platform :ios, '8.0'

  target 'TodayNew' do
  pod 'AFNetworking', '~> 3.0'
  pod 'MBProgressHUD', '~> 0.9.1'
  pod 'SDWebImage'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'Reachability'
  pod 'FMDB'
  pod 'SGPagingView'
  pod 'SVProgressHUD'
  pod 'ZFPlayer'
  pod 'YYText'
  pod 'pop'

end